### ISSUE TITLE
aktive Patches not loading

### ISSUE THREAD

**Issue by Fall0n** [GoldHEN/GoldHEN_Plugins_Repository#23]
Patches is not working on games have try elden ring 1.05 no pop up when i start game. Some one help me get it working?

**Comment by Dmitriy260190** [comment]
I wrote incorrectly, I apologize. 
I tried to activate patches for the above games. anlok fps, skip intro, etc. does not work in all these games. what is the problem I can not understand. in the menu Goldhen plugins are activated, of course.

**Comment by preston176** [comment]
anyone having this issue

> 
delete goldhen folder then reboot then run goldhen 2.3 then enable 

IT WILL WORK

**Comment by Dmitriy260190** [comment]
Thank you so much, that helped!

**Comment by illusion0001** [comment]
Seems solved. Closing
