### ISSUE TITLE
Question: aio_fix_505.prx

### ISSUE THREAD

**Issue by Sylntnyt** [GoldHEN/GoldHEN_Plugins_Repository#30]
I saw this was one of the new plugins made by jocover and I'm assuming by its name it's something that only affects 5.05 and based on the source code has something to do with async. I'm just trying to get more clarification/information on what exactly this plugin does since there isn't anything in the Readme or anywhere else I've looked online.

**Comment by jocover** [comment]
some backport games in 5.05 system has asynchronous I/O isuess,this plugin can fix that
