### ISSUE TITLE
aio_fix_5.05.prx Hogwarts Legacy Warning Screen

### ISSUE THREAD

**Issue by Sylntnyt** [GoldHEN/GoldHEN_Plugins_Repository#36]
System: PS4 Fat
FW: 5.05
HEN: GoldHEN 2.4b13

    With the latest plugins and aio_fix_505.prx activated under "default" in plugins.ini, Hogwarts Legacy gets stuck at the warning screen and after some time the music from the title screen plays and pushing X (or any other button) does not allow advancement past the screen. A temporary fix is to comment out (disable) the line for the plugin in plugins.ini which will unfortunately disable it for any backport/game that needs the plugin active. Not sure if there's a list of which backports/games require the plugin to be active (I know plugins can be a per game id basis instead of under the blanket coverage of "default") but this bug/issue gave me an idea for an enhancement that I'll also make a post for. For now I've yet to have any need for the plugin being active, but I do so just in case.

**Comment by illusion0001** [comment]
Not an issue
