### ISSUE TITLE
Can't build game_patch

### ISSUE THREAD

**Issue by rfoodxmodz** [GoldHEN/GoldHEN_Plugins_Repository#66]
ld.lld: error: undefined symbol: module_start

can't build the game_patch.prx I think the issue from crtprx.c or something

**Comment by illusion0001** [comment]
Post full build log

**Comment by rfoodxmodz** [comment]
Microsoft Windows [Version 10.0.19045.3086]
(c) Microsoft Corporation. All rights reserved.

C:\Users\koora>C:\Users\koora\Desktop\MY-LINUX-FILES-LATEST\GoldHEN_Plugins_Repository-main\build.bat
[+] Workdir: C:\Users\koora\Desktop\MY-LINUX-FILES-LATEST\GoldHEN_Plugins_Repository-main
[+] Output directory: C:\Users\koora\Desktop\MY-LINUX-FILES-LATEST\GoldHEN_Plugins_Repository-main\bin\plugins
'git' is not recognized as an internal or external command,
operable program or batch file.
'git' is not recognized as an internal or external command,
operable program or batch file.
'git' is not recognized as an internal or external command,
operable program or batch file.
[+] Building the plugins
plugin_src\afr\source\main.c:6:10: fatal error: 'plugin_common.h' file not found
#include "plugin_common.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
[+] afr
[+]  "plugin_src\afr\build\plugin_common.c.o" "plugin_src\afr\build\main.c.o"
ld.lld: error: cannot open plugin_src\afr\build\main.c.o: no such file or directory
Failed to build FSELF: open plugin_src\afr\build\afr.elf: The system cannot find the file specified.
The system cannot find the file specified.
plugin_src\aio_fix_505\source\main.c:4:10: fatal error: 'plugin_common.h' file not found
#include "plugin_common.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
[+] aio_fix_505
[+]  "plugin_src\aio_fix_505\build\plugin_common.c.o" "plugin_src\aio_fix_505\build\main.c.o"
ld.lld: error: cannot open plugin_src\aio_fix_505\build\main.c.o: no such file or directory
Failed to build FSELF: open plugin_src\aio_fix_505\build\aio_fix_505.elf: The system cannot find the file specified.
The system cannot find the file specified.
plugin_src\button_swap\source\main.c:4:10: fatal error: 'plugin_common.h' file not found
#include "plugin_common.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
[+] button_swap
[+]  "plugin_src\button_swap\build\plugin_common.c.o" "plugin_src\button_swap\build\main.c.o"
ld.lld: error: cannot open plugin_src\button_swap\build\main.c.o: no such file or directory
Failed to build FSELF: open plugin_src\button_swap\build\button_swap.elf: The system cannot find the file specified.
The system cannot find the file specified.
plugin_src\fliprate_remover\source\main.c:10:10: fatal error: 'plugin_common.h' file not found
#include "plugin_common.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
[+] fliprate_remover
[+]  "plugin_src\fliprate_remover\build\plugin_common.c.o" "plugin_src\fliprate_remover\build\main.c.o"
ld.lld: error: cannot open plugin_src\fliprate_remover\build\main.c.o: no such file or directory
Failed to build FSELF: open plugin_src\fliprate_remover\build\fliprate_remover.elf: The system cannot find the file specified.
The system cannot find the file specified.
plugin_src\force_1080p_display\source\main.c:8:10: fatal error: 'plugin_common.h' file not found
#include "plugin_common.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
[+] force_1080p_display
[+]  "plugin_src\force_1080p_display\build\plugin_common.c.o" "plugin_src\force_1080p_display\build\main.c.o"
ld.lld: error: cannot open plugin_src\force_1080p_display\build\main.c.o: no such file or directory
Failed to build FSELF: open plugin_src\force_1080p_display\build\force_1080p_display.elf: The system cannot find the file specified.
The system cannot find the file specified.
plugin_src\force_30_fps\source\main.c:7:10: fatal error: 'plugin_common.h' file not found
#include "plugin_common.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
[+] force_30_fps
[+]  "plugin_src\force_30_fps\build\plugin_common.c.o" "plugin_src\force_30_fps\build\main.c.o"
ld.lld: error: cannot open plugin_src\force_30_fps\build\main.c.o: no such file or directory
Failed to build FSELF: open plugin_src\force_30_fps\build\force_30_fps.elf: The system cannot find the file specified.
The system cannot find the file specified.
plugin_src\gamepad_helper\source\config.c:7:10: fatal error: 'plugin_common.h' file not found
#include "plugin_common.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
plugin_src\gamepad_helper\source\main.c:4:10: fatal error: 'plugin_common.h' file not found
#include "plugin_common.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
[+] gamepad_helper
[+]  "plugin_src\gamepad_helper\build\plugin_common.c.o" "plugin_src\gamepad_helper\build\config.c.o" "plugin_src\gamepad_helper\build\main.c.o"
ld.lld: error: cannot open plugin_src\gamepad_helper\build\config.c.o: no such file or directory
ld.lld: error: cannot open plugin_src\gamepad_helper\build\main.c.o: no such file or directory
Failed to build FSELF: open plugin_src\gamepad_helper\build\gamepad_helper.elf: The system cannot find the file specified.
The system cannot find the file specified.
plugin_src\game_call_example\source\main.c:12:10: fatal error: 'plugin_common.h' file not found
#include "plugin_common.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
[+] game_call_example
[+]  "plugin_src\game_call_example\build\plugin_common.c.o" "plugin_src\game_call_example\build\main.c.o"
ld.lld: error: cannot open plugin_src\game_call_example\build\main.c.o: no such file or directory
Failed to build FSELF: open plugin_src\game_call_example\build\game_call_example.elf: The system cannot find the file specified.
The system cannot find the file specified.
[+] game_patch_test
[+]  "plugin_src\game_patch_test\build\plugin_common.c.o"
ld.lld: error: undefined symbol: module_start
>>> referenced by crtprx.c
>>>               crtprx.o:(_init) in archive C:\GoldHEN_Plugins_SDK-main\libGoldHEN_Hook.a

ld.lld: error: undefined symbol: module_stop
>>> referenced by crtprx.c
>>>               crtprx.o:(_fini) in archive C:\GoldHEN_Plugins_SDK-main\libGoldHEN_Hook.a
Failed to build FSELF: open plugin_src\game_patch_test\build\game_patch_test.elf: The system cannot find the file specified.
The system cannot find the file specified.
plugin_src\no_share_watermark\source\main.c:12:10: fatal error: 'plugin_common.h' file not found
#include "plugin_common.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
[+] no_share_watermark
[+]  "plugin_src\no_share_watermark\build\plugin_common.c.o" "plugin_src\no_share_watermark\build\main.c.o"
ld.lld: error: cannot open plugin_src\no_share_watermark\build\main.c.o: no such file or directory
Failed to build FSELF: open plugin_src\no_share_watermark\build\no_share_watermark.elf: The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
plugin_src\plugin_loader\source\config.c:7:10: fatal error: 'plugin_common.h' file not found
#include "plugin_common.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
plugin_src\plugin_loader\source\main.c:15:10: fatal error: 'plugin_common.h' file not found
#include "plugin_common.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
[+] plugin_loader
[+]  "plugin_src\plugin_loader\build\plugin_common.c.o" "plugin_src\plugin_loader\build\config.c.o" "plugin_src\plugin_loader\build\main.c.o"
ld.lld: error: cannot open plugin_src\plugin_loader\build\config.c.o: no such file or directory
ld.lld: error: cannot open plugin_src\plugin_loader\build\main.c.o: no such file or directory
Failed to build FSELF: open plugin_src\plugin_loader\build\plugin_loader.elf: The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
plugin_src\plugin_template\source\main.c:5:10: fatal error: 'plugin_common.h' file not found
#include "plugin_common.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
[+] plugin_template
[+]  "plugin_src\plugin_template\build\plugin_common.c.o" "plugin_src\plugin_template\build\main.c.o"
ld.lld: error: cannot open plugin_src\plugin_template\build\main.c.o: no such file or directory
Failed to build FSELF: open plugin_src\plugin_template\build\plugin_template.elf: The system cannot find the file specified.
The system cannot find the file specified.
[+] All done

C:\Users\koora>

**Comment by illusion0001** [comment]
Windows build script isn't really supported anymore. Use WSL

**Comment by rfoodxmodz** [comment]
ok thanks
