### ISSUE TITLE
Plugin arguments

### ISSUE THREAD

**Issue by KrisztianKende** [GoldHEN/GoldHEN_Plugins_Repository#7]
The _module_start()_ function has _argv_ and _args_ parameters, but there is no way to pass arguments to the plugins.
It would be nice if we could pass args through the plugins.ini file.
```
[CUSAxxxxx]
/data/GoldHEN/plugins/<plugin_name>.prx <arg1> <arg2>
```
I've created a plugin that changes the system language detected by games, but it would be much nicer if we didn't need a separate plugin for each language. So if the system language is English, but I want the game to start in German, another in Hungarian, then it would look like this:

```
[CUSA12345]
/data/GoldHEN/plugins/system_language_change.prx German

[CUSA12346]
/data/GoldHEN/plugins/system_language_change.prx Hungarian
```
This would be especially useful for game translations. Because it is not always possible or optimal to replace the English subtitles, but some games set the subtitle according to the language of the system.

**Comment by nkrapivin** [comment]
Right now we don't know well how PS4 passes arguments to modules at load, so the best you can do is make your own config file in `/data/GoldHEN` and parse it yourself.

**Comment by KrisztianKende** [comment]
I think it's fine if we can't passes arguments to modules at load. We can create a function that will reparse the plugins.ini file, but currently the plugin won't load if there are any arguments.
For simplicity, it would be better if arguments could be specified in the plugins.ini file. It would be more user friendly.

Currently it only works like this:
```
[CUSAxxxxx]
/data/GoldHEN/plugins/<plugin_name>.prx ;arg1 arg2
```

**Comment by nkrapivin** [comment]
Yeah this one *should* be possible to implement.

**Comment by KrisztianKende** [comment]
OK, so I've [done it this way for now](https://github.com/KrisztianKende/GoldHEN_Plugins/tree/main/system_language_override), with semicolon. It's actually not that bad, it's usable, just not that pretty.

**Comment by illusion0001** [comment]
You can do `=` for better look. `;` are for comments.

**Comment by illusion0001** [comment]
https://github.com/GoldHEN/GoldHEN_Plugins_Repository/blob/89d8a33f2ae9c5812a7863dc253e209403ff379b/plugin_src/plugin_loader/source/config.c#L194-L205

**Comment by KrisztianKende** [comment]
Thanks, that was a very good suggestion, so [I modified the plugin](https://github.com/KrisztianKende/GoldHEN_Plugins/tree/main/system_language_override). It's much nicer now. :-)

**Comment by KrisztianKende** [comment]
Thanks, this issue is resolved now.
